### ISSUE TITLE
Info not showing up properly

### ISSUE THREAD

**Issue by zkzipoo** [gazzasat/huawei-cpe#1]
Hi, 

Thanks a lot for sharing your code here.
If you have time, could you please help to check my situation here.

```
Hardware versionWL1H112M
Software version10.0.5.11(H351SP2C983)
Web UI versionWEBUI 10.0.5.1(W2SP5C7110)
Configuration file versionH112-370-CUST 8.0.1.2(C1217)
```

And mine here just showed:

<img width="953" alt="Screenshot 2022-11-25 221110" src="https://user-images.githubusercontent.com/3366892/204059369-51388e0c-54af-4cf7-b783-3cea6a4990ba.png">

And to clarify, I think I do have 5g singal here with the green light on 5g and 

<img width="788" alt="Screenshot 2022-11-25 221348" src="https://user-images.githubusercontent.com/3366892/204059509-0929ad79-21c4-4c6a-8fe9-70eb2e2db48e.png">

Any thoughts, thanks

**Comment by gazzasat** [comment]
Hi,

glad you are finding this code useful.  I normally only see that behaviour when the 5G nr data is not available, typically because the device has fallen back to 4G only.

The data capture uses the same as the api call the '_Advanced->System->Device Information_' menu
![image](https://user-images.githubusercontent.com/104030357/204102434-f1da7287-300d-4761-86cb-e6880c198b66.png)
what does this say on your box?

The raw api call used is as below if you can compare result.  Perhaps there is some slight mismatch with parameter naming on your firmware release:
`view-source:https://192.168.8.1/api/device/signal`
which returns the following payload:
![image](https://user-images.githubusercontent.com/104030357/204102642-aa9e0931-4cf4-46bb-8483-25cc83049c9a.png)

Let me know what you see!

**Comment by gingerbeardman** [comment]
For the record, and in light of there being no Discussion area in this repo, I'd like to add that this script is working for me - cheers!

With a little bit of messing with the BANDS, my router now seems to prefer the 3rd closest tower with 5G here in Liverpool. I'm not confident it's any better than the default, perhaps marginally, but it was fun to do so I'm happy.

<img width="301" alt="image" src="https://github.com/gazzasat/huawei-cpe/assets/49612/8b1fec4d-1250-42e8-81c4-69224c5bd4db">

```
<response>
<pci>460</pci>
<sc></sc>
<cell_id>378696</cell_id>
<rsrq>-5.0dB</rsrq>
<rsrp>-82dBm</rsrp>
<rssi>&lt;=-113dBm</rssi>
<sinr>11dB</sinr>
<rscp></rscp>
<ecio></ecio>
<mode>7</mode>
<ulbandwidth>10MHz</ulbandwidth>
<dlbandwidth>10MHz</dlbandwidth>
<txpower>PPusch:0dBm PPucch:-2dBm PSrs:0dBm PPrach:0dBm</txpower>
<tdd></tdd>
<ul_mcs>mcsUpCarrier1:29</ul_mcs>
<dl_mcs>mcsDownCarrier1Code0:3 mcsDownCarrier1Code1:21</dl_mcs>
<earfcn>DL:99 UL:18099</earfcn>
<rrc_status>1</rrc_status>
<rac></rac>
<lac></lac>
<tac>3079</tac>
<band>1</band>
<nei_cellid>No1:459</nei_cellid>
<plmn>23420</plmn>
<ims></ims>
<wdlfreq></wdlfreq>
<lteulfreq>19299</lteulfreq>
<ltedlfreq>21199</ltedlfreq>
<transmode>TM[0]</transmode>
<enodeb_id>0001479</enodeb_id>
<cqi0>32639</cqi0>
<cqi1>32639</cqi1>
<ulfrequency>1929900kHz</ulfrequency>
<dlfrequency>2119900kHz</dlfrequency>
<nrulbandwidth>100MHz</nrulbandwidth>
<nrdlbandwidth>100MHz</nrdlbandwidth>
<nrulmcs>NRmcsUpCarrier1:29</nrulmcs>
<nrdlmcs>NRmcsDownCarrier1Code0:0 NRmcsDownCarrier1Code1:0</nrdlmcs>
<nrtxpower>PPusch:20dBm PPucch:20dBm PSrs:20dBm PPrach:20dBm</nrtxpower>
<nrearfcn>DL:642000 UL:642000</nrearfcn>
<nrulfreq>3630000kHz</nrulfreq>
<nrdlfreq>3630000kHz</nrdlfreq>
<nrsinr>2dB</nrsinr>
<nrrsrp>-108dBm</nrrsrp>
<nrrsrq>-12.0dB</nrrsrq>
<arfcn></arfcn>
<bsic></bsic>
<rxlev></rxlev>
</response>
```

**Comment by gazzasat** [comment]
Appreciated.  Enjoy the 5G !
